# coding: utf-8

"""
    Game Voting API

    This API is meant as baseline functionality for a game voting tool that is combined with an Asyncapi specification for all the interactive pieces.

    The version of the OpenAPI document: 2.0.0
    Contact: philipp.schmurr@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from gvt_server.apis.game_api import router as GameApiRouter
from gvt_server.apis.image_api import router as ImageApiRouter
from gvt_server.apis.user_api import router as UserApiRouter
try:
    from gvt_server.impl.lifespan import before_app_start
except ImportError:
    def before_app_start(x): return


app = FastAPI(
    title="Game Voting API",
    description="This API is meant as baseline functionality for a game voting tool that is combined with an Asyncapi specification for all the interactive pieces.",
    version="2.0.0",
)

app.include_router(GameApiRouter)
app.include_router(ImageApiRouter)
app.include_router(UserApiRouter)

before_app_start(app)
