# coding: utf-8

"""
    Game Voting API

    This API is meant as baseline functionality for a game voting tool that is combined with an Asyncapi specification for all the interactive pieces.

    The version of the OpenAPI document: 2.0.0
    Contact: philipp.schmurr@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gvt_server.models.game_votes import GameVotes
from gvt_server.models.user_votes import UserVotes
from sqlmodel import SQLModel, Field, Relationship
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class VotingSession(SQLModel):
    """
    VotingSession
    """ # noqa: E501
    id: StrictStr
    game_votes: List[GameVotes] = Field(alias="gameVotes")
    user_votes: List[UserVotes] = Field(alias="userVotes")
    start_time: Optional[datetime] = Field(default=None, alias="startTime")
    finish_time: Optional[datetime] = Field(default=None, alias="finishTime")
    cancel_time: Optional[datetime] = Field(default=None, alias="cancelTime")
    __properties: ClassVar[List[str]] = ["id", "gameVotes", "userVotes", "startTime", "finishTime", "cancelTime"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VotingSession from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in game_votes (list)
        _items = []
        if self.game_votes:
            for _item in self.game_votes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['gameVotes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in user_votes (list)
        _items = []
        if self.user_votes:
            for _item in self.user_votes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['userVotes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of VotingSession from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in VotingSession) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "gameVotes": [GameVotes.from_dict(_item) for _item in obj.get("gameVotes")] if obj.get("gameVotes") is not None else None,
            "userVotes": [UserVotes.from_dict(_item) for _item in obj.get("userVotes")] if obj.get("userVotes") is not None else None,
            "startTime": obj.get("startTime"),
            "finishTime": obj.get("finishTime"),
            "cancelTime": obj.get("cancelTime")
        })
        return _obj


