openapi: 3.1.0
info:
  title: Game Voting API
  description: |-
    This API is meant as baseline functionality for a game voting tool that is combined with an Asyncapi specification for all the interactive pieces.

  # termsOfService: http://swagger.io/terms/
  contact:
    email: philipp.schmurr@gmail.com
  license:
    name: MIT
    identifier: MIT
    # url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.0.0
# externalDocs:
  # description: Find out more about Swagger
  # url: http://swagger.io
servers:
  # - url: https://petstore3.swagger.io/api/v3
  - url: http://DESKTOP-JSU69NL:1337
tags:
  - name: game
    description: Everything about available games
  - name: user
    description: Operations about user
  - name: image
    description: Operations to deliver game images
paths:
  /images/{game_id}:
    get:
      tags:
        - image
      summary: Get a certain image
      description: 'Receive the requested image from the database'
      operationId: get_image
      parameters:
        - name: game_id
          in: path
          required: true
          description: ID of the game to get the image for
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          # content:
          #   image/png:
          #     schema:
          #       type: string
          #       format: binary
        '404':
          description: not found
  
  /games:
    get:
      tags:
        - game
      summary: Get list of supported games
      description: 'Receive game list'
      operationId: get_games
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
    post:
      tags:
        - game
      summary: Attempt to add a new game
      description: Add a new game from a data record
      operationId: create_game
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
          
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Invalid input or game id already taken
        '422':
          description: Validation exception
  /games/from-steam:
    post:
      tags:
        - game
      summary: Attempt to add a game from a steam id
      description: Scrapes the steam store for data
      operationId: create_game_from_steam
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Invalid input or game id already taken
        '422':
          description: Validation exception

  /user/login:
    post:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: login_user
      requestBody:
        description: Desired user name
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Userame already in use

  /voting/{session_id}/games/{game_id}:
    post:
      tags:
        - voting
      summary: Attempt to add a game to the voting
      description: Attempt to add a game to the active voting by its ID
      operationId: add_game_to_voting
      parameters:
        - name: session_id
          in: path
          required: true
          description: the ID of the session to add the game to
          schema:
            type: string
        - name: game_id
          in: path
          required: true
          description: ID of the game to add to the voting
          schema:
            type: string
      responses:
        '200':
          description: game added successfully
        '400':
          description: game could not be added
        '404':
          description: game could not be found
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: string
          # x-python-type: "str = Field(primary_key='True', nullable=False)"
        name:
          type: string
        steamAppid:
          type: string
#        detailed_description:
#          type: string
#        description:
#          type: string
        coverUrl:
          type: string
          format: url
#        categories:
#          type: array
#          items:
#            type: string
#        genres:
#          type: array
#          items:
#            type: string
#        release_date:
#          type: string
#          format: date-time
#        Genre:
#          type: array
#          items:
#            type: string
#        MP:
#          type: string
#        Type:
#          type: string
#        Toplevel:
#          type: string
#        Meta:
#          type: array
#          items:
#            type: string
#        Parent:
#          type: [string, null]
#        Children:
#          type: array
#          items:
#            type: string
#        Readme:
#          type: string
      required:
        - id
        - name
        - coverUrl
#        - Parent
#        - Children
#        - Meta
#        - Toplevel
#        - Type
#        - MP
#        - Genre

#    user_session:
#      type: object
#      properties:
#        id:
#          type: string
#        user_name:
#          type: string
#        login_time:
#          type: string
#          format: date-time
#        logout_time:
#          type: string
#          format: date-time
##        avatar:
##          type: string
##          format: url
#      required:
#        - id
#        - user_name
    VotingSession:
      type: object
      required:
        - id
        - start_time
      properties:
        id:
          type: string
#        participants:
#          type: array
#          items:
#            $ref: '#/components/schemas/Player'
        start_time:
          type: string
          format: date-time
        games:
          type: array
          items:
            $ref: '#/components/schemas/Game'
          maxItems: 6
#        game_id_1:
#          type: ["string", "null"]
#        game_id_2:
#          type: ["string", "null"]
#        game_id_3:
#          type: ["string", "null"]
#        game_id_4:
#          type: ["string", "null"]
#        game_id_5:
#          type: ["string", "null"]
#        game_id_6:
#          type: ["string", "null"]

        
    GameVotes:
      type: object
      properties:
        game_id:
          type: string
        likes:
          type: integer
        abstains:
          type: integer
        dislikes:
          type: integer
      required:
        - game_id
        - likes
        - abstains
        - dislikes
    
    VotingSessionPublic:
      type: object
      properties:
        id:
          type: string
          format: date-time
        game_votes:
          type: array
          items:
            $ref: '#/components/schemas/GameVotes'
        is_finished:
          type: boolean
        


        
#    Vote:
#      type: object
#      properties:
#        voting_session_id:
#          type: string
#        game_id:
#          type: string
#          # x-python-type: 'StrictStr = Field(foreign_key="game.id")'
#        # game:
#          # $ref: '#/components/schemas/Game'
#          # x-python-type: 'Game = Relationship()'
#        user_name:
#          type: string
#        value:
#          type: integer
#          minimum: -1
#          maximum: 1
#      required:
#        - voting_session_id
#        - game_id
#        - user_name
#        - value
      
  # requestBodies:
  #   Pet:
  #     description: Pet object that needs to be added to the store
  #     content:
  #       application/json:
  #         schema:
  #           $ref: '#/components/schemas/Pet'
  #       application/xml:
  #         schema:
  #           $ref: '#/components/schemas/Pet'
  #   UserArray:
  #     description: List of user object
  #     content:
  #       application/json:
  #         schema:
  #           type: array
  #           items:
  #             $ref: '#/components/schemas/User'
  # securitySchemes:
  #   petstore_auth:
  #     type: oauth2
  #     flows:
  #       implicit:
  #         authorizationUrl: https://petstore3.swagger.io/oauth/authorize
  #         scopes:
  #           write:pets: modify pets in your account
  #           read:pets: read your pets
  #   api_key:
  #     type: apiKey
  #     name: api_key
  #     in: header
