openapi: 3.1.0
info:
  title: Game Voting API
  description: |-
    This API is meant as baseline functionality for a game voting tool that is combined with an Asyncapi specification for all the interactive pieces.

  # termsOfService: http://swagger.io/terms/
  contact:
    email: philipp.schmurr@gmail.com
  license:
    name: MIT
    identifier: MIT
    # url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.0.0
# externalDocs:
  # description: Find out more about Swagger
  # url: http://swagger.io
servers:
  # - url: https://petstore3.swagger.io/api/v3
  - url: http://DESKTOP-JSU69NL:1337
tags:
  - name: game
    description: Everything about available games
  - name: user
    description: Operations about user
  - name: image
    description: Operations to deliver game images
paths:
  /images/{game_id}:
    get:
      tags:
        - image
      summary: Get a certain image
      description: 'Receive the requested image from the database'
      operationId: get_image
      parameters:
        - name: game_id
          in: path
          required: true
          description: ID of the game to get the image for
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          # content:
          #   image/png:
          #     schema:
          #       type: string
          #       format: binary
        '404':
          description: not found
  
  /games:
    get:
      tags:
        - game
      summary: Get list of supported games
      description: 'Receive game list'
      operationId: get_games
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
    post:
      tags:
        - game
      summary: Attempt to add a new game
      description: Add a new game from a data record
      operationId: create_game
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
          
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Invalid input or game id already taken
        '422':
          description: Validation exception
  /games/from-steam:
    post:
      tags:
        - game
      summary: Attempt to add a game from a steam id
      description: Scrapes the steam store for data
      operationId: create_game_from_steam
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Invalid input or game id already taken
        '422':
          description: Validation exception

  /user/login:
    post:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: login_user
      requestBody:
        description: Desired user name
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Userame already in use
  /voting-session/{session_id}/participant/{user_id}/reset:
    put:
      tags:
        - voting
      summary: Indicate if you want to set or revoke your reset vote
      description: Players can indicate if they want to reset or re-roll the voting session a majority triggers that accordingly.
      operationId: set_reset_vote
      parameters:
        - name: session_id
          in: path
          required: true
          description: the ID of the session to add the game to
          schema:
            type: string
        - name: user_id
          in: path
          required: true
          description: the user that attempts to add the game
          schema:
            type: string
      requestBody:
        required: true
        description: the value of the vote to be cast
        content:
          application/json:
            schema:
              type: integer
              minValue: 0
              maxValue: 1
      responses:
        '200':
          description: vote cast successfully
        '400':
          description: vote could not be cast
        '404':
          description: session, or user could not be found
  /voting-session/{session_id}/participant/{user_id}/games/{game_id}:
    post:
      tags:
        - voting
      summary: Attempt to add a game to the voting
      description: Attempt to add a game to the active voting by its ID
      operationId: add_game_to_voting
      parameters:
        - name: session_id
          in: path
          required: true
          description: the ID of the session to add the game to
          schema:
            type: string
        - name: user_id
          in: path
          required: true
          description: the user that attempts to add the game
          schema:
            type: string
        - name: game_id
          in: path
          required: true
          description: ID of the game to add to the voting
          schema:
            type: string
      responses:
        '200':
          description: game added successfully
        '400':
          description: game could not be added
        '404':
          description: game could not be found
  /voting-session/{session_id}/participant/{user_id}/games/{game_id}/vote:
    post:
      tags:
        - voting
      summary: Set a voting value
      description: Set your voting value for a specific game in a specific session
      operationId: cast_vote
      parameters:
        -   name: session_id
            in: path
            required: true
            description: the ID of the session to cast the vote in
            schema:
              type: string
        -   name: user_id
            in: path
            required: true
            description: the user that casts the vote
            schema:
              type: string
        -   name: game_id
            in: path
            required: true
            description: the game the vote is cast for
            schema:
              type: string
      requestBody:
        required: true
        description: the value of the vote to be cast
        content:
          application/json:
            schema:
              type: integer
      responses:
        '200':
          description: vote cast successfully
        '400':
          description: vote could not be cast
        '404':
          description: session, user, or game could not be found
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        steamAppid:
          type: string
        coverUrl:
          type: string
          format: url
      required:
        - id
        - name
        - coverUrl
    VotingSession:
      type: object
      required:
        - id
        - start_time
        - gameVotes
        - userVotes
        - resetVotes
      properties:
        id:
          type: string
        startTime:
          type: string
          format: date-time
        finishTime:
          type: string
          format: date-time
        cancelTime:
          type: string
          format: date-time
        gameVotes:
          type: array
          items:
            $ref: '#/components/schemas/GameVotes'
        userVotes:
          type: array
          items:
            $ref: '#/components/schemas/UserVotes'
        resetVotes:
          type: array
          items:
            $ref: '#/components/schemas/UserResetVote'
    UserGameVote:
      type: object
      properties:
        userName:
          type: string
        value:
          type: integer
      required:
        - userName
        - value
    UserResetVote:
      type: object
      properties:
        userName:
          type: string
        value:
          type: integer
          minValue: 0
          maxValue: 1
      required:
        - userName
        - value
    GameVotes:
      type: object
      properties:
        game:
          $ref: '#/components/schemas/Game'
        likes:
          type: integer
        abstains:
          type: integer
        dislikes:
          type: integer
        userVotes:
          type: array
          items:
            $ref: '#/components/schemas/UserGameVote'
      required:
        - game
        - likes
        - abstains
        - dislikes
        - userVotes
    UserVotes:
      type: object
      properties:
        userName:
          type: string
        votes:
          type: number
      required:
        - userName
        - votes

    # this enum is only used as a convenience to see available message types - it does
    #  hold no meaning in the oneOf pattern
    WebsocketMessageType:
      type: string
      enum:
        - voting_session
        - result
        - cancellation
    WebsocketMessage:
      oneOf:
        - $ref: '#/components/schemas/VotingSessionMessage'
        - $ref: '#/components/schemas/VotingResultMessage'
        - $ref: '#/components/schemas/VotingCancellationMessage'
      discriminator:
        propertyName: type
        mapping:
          voting_session: '#/components/schemas/VotingSessionMessage'
          result: '#/components/schemas/VotingResultMessage'
          cancellation: '#/components/schemas/VotingCancellationMessage'

    VotingSessionMessage:
      type: object
      required:
        - type
        - body
      properties:
        type:
          # $ref: '#/components/schemas/WebsocketMessageType'
          type: string
          default: voting_session
          # const: voting_session
        body:
          $ref: '#/components/schemas/VotingSession'
    VotingResultMessage:
      type: object
      required:
        - type
        - body
      properties:
        type:
          type: string
          # $ref: '#/components/schemas/WebsocketMessageType'
          default: result
          # const: result
        body:
          type: array
          items:
            $ref: '#/components/schemas/GameVotes'
    VotingCancellationMessage:
      type: object
      required:
        - type
        - body
      properties:
        type:
          type: string
          # $ref: '#/components/schemas/WebsocketMessageType'
          # const: cancellation
          default: cancellation
        body:
          type: array
          items:
            $ref: '#/components/schemas/UserResetVote'
