# coding: utf-8

"""
    Game Voting API

    This API is meant as baseline functionality for a game voting tool that is combined with an Asyncapi specification for all the interative pieces.

    The version of the OpenAPI document: 2.0.0
    Contact: philipp.schmurr@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI, WebSocket

from gv_server.apis.game_api import router as GameApiRouter
from gv_server.apis.image_api import router as ImageApiRouter
from gv_server.apis.user_api import router as UserApiRouter

from fastapi.middleware.cors import CORSMiddleware


origins = [
    "*"
]

app = FastAPI(
    title="Game Voting API",
    description="This API is meant as baseline functionality for a game voting tool that is combined with an Asyncapi specification for all the interative pieces.",
    version="2.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(GameApiRouter)
app.include_router(ImageApiRouter)
app.include_router(UserApiRouter)

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    while True:
        data = await websocket.receive_text()
        await websocket.send_text(f"Message text was: {data}")




